// <auto-generated />
namespace BeardBook.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Conversation_Active_Field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Conversation_Active_Field));
        
        string IMigrationMetadata.Id
        {
            get { return "201706011348584_Conversation_Active_Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
