// <auto-generated />
namespace BeardBook.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FilePost_navigation_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FilePost_navigation_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201702271443275_File-Post_navigation_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
